// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoiApi.Data;

#nullable disable

namespace PoiApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420170526_AddQrCodeUrlToShop")]
    partial class AddQrCodeUrlToShop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("POITranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("POIId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("POIId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("POITranslations");
                });

            modelBuilder.Entity("PoiApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PoiApi.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("PoiApi.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("POIId")
                        .HasColumnType("int");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("POIId");

                    b.HasIndex("ShopId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("PoiApi.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("PoiApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PoiApi.Models.POI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("MenuImagesUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("POIs");
                });

            modelBuilder.Entity("PoiApi.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("PoiApi.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "ADMIN"
                        },
                        new
                        {
                            Id = -2,
                            Name = "OWNER"
                        },
                        new
                        {
                            Id = -3,
                            Name = "USER"
                        });
                });

            modelBuilder.Entity("PoiApi.Models.ServicePackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowAiPlanAccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowAudioAccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowChatbotAccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowTinderAccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxStores")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("YearlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ServicePackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowAiPlanAccess = false,
                            AllowAudioAccess = false,
                            AllowChatbotAccess = false,
                            AllowTinderAccess = false,
                            Audience = "OWNER",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói khởi đầu cho shop kinh doanh nhỏ.",
                            Features = "Hiển thị trên bản đồ|Tối đa 1 gian hàng|1 Menu, không giới hạn món|Hỗ trợ qua email|!Badge trên app|!Ưu tiên đề xuất|!Thống kê nâng cao",
                            IsActive = true,
                            MaxStores = 1,
                            MonthlyPrice = 99000m,
                            Name = "Basic",
                            Tier = "Basic",
                            YearlyPrice = 990000m
                        },
                        new
                        {
                            Id = 2,
                            AllowAiPlanAccess = false,
                            AllowAudioAccess = false,
                            AllowChatbotAccess = false,
                            AllowTinderAccess = false,
                            Audience = "OWNER",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dành cho shop muốn tăng độ nhận diện và hiệu quả.",
                            Features = "Tất cả tính năng Basic|Tối đa 3 gian hàng|Badge \"Premium\" trên app|Ưu tiên đề xuất (score +50)|Thống kê nâng cao|Hỗ trợ ưu tiên|!Quảng cáo banner",
                            IsActive = true,
                            MaxStores = 3,
                            MonthlyPrice = 299000m,
                            Name = "Premium",
                            Tier = "Premium",
                            YearlyPrice = 2990000m
                        },
                        new
                        {
                            Id = 3,
                            AllowAiPlanAccess = false,
                            AllowAudioAccess = false,
                            AllowChatbotAccess = false,
                            AllowTinderAccess = false,
                            Audience = "OWNER",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Đặc quyền cao cấp nhất cho doanh nghiệp lớn.",
                            Features = "Tất cả tính năng Premium|Tối đa 5 gian hàng|Badge \"VIP\" trên app|Top đề xuất (score +100)|Thống kê chi tiết|Quảng cáo trên banner|Hỗ trợ riêng 24/7",
                            IsActive = true,
                            MaxStores = 5,
                            MonthlyPrice = 599000m,
                            Name = "VIP",
                            Tier = "VIP",
                            YearlyPrice = 5990000m
                        },
                        new
                        {
                            Id = 4,
                            AllowAiPlanAccess = false,
                            AllowAudioAccess = true,
                            AllowChatbotAccess = false,
                            AllowTinderAccess = false,
                            Audience = "USER",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói nghe thuyết minh cơ bản.",
                            Features = "Nghe thuyết minh 3 ngôn ngữ|Hỗ trợ review sau khi nghe",
                            IsActive = false,
                            MaxStores = 0,
                            MonthlyPrice = 49000m,
                            Name = "Audio Starter",
                            Tier = "AudioBasic",
                            YearlyPrice = 490000m
                        },
                        new
                        {
                            Id = 5,
                            AllowAiPlanAccess = false,
                            AllowAudioAccess = true,
                            AllowChatbotAccess = false,
                            AllowTinderAccess = false,
                            Audience = "USER",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói nghe thuyết minh mở rộng.",
                            Features = "Nghe thuyết minh 3 ngôn ngữ|Ưu tiên audio mới",
                            IsActive = false,
                            MaxStores = 0,
                            MonthlyPrice = 99000m,
                            Name = "Audio Plus",
                            Tier = "AudioPremium",
                            YearlyPrice = 990000m
                        },
                        new
                        {
                            Id = 6,
                            AllowAiPlanAccess = false,
                            AllowAudioAccess = true,
                            AllowChatbotAccess = false,
                            AllowTinderAccess = false,
                            Audience = "USER",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gói audio cao cấp.",
                            Features = "Nghe thuyết minh 3 ngôn ngữ|Hỗ trợ ưu tiên",
                            IsActive = false,
                            MaxStores = 0,
                            MonthlyPrice = 199000m,
                            Name = "Audio Premium",
                            Tier = "AudioVIP",
                            YearlyPrice = 1990000m
                        },
                        new
                        {
                            Id = 7,
                            AllowAiPlanAccess = false,
                            AllowAudioAccess = true,
                            AllowChatbotAccess = false,
                            AllowTinderAccess = false,
                            Audience = "USER",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mở khóa thuyết minh ẩm thực tự động khi đến gần các gian hàng. Sử dụng trong 1 ngày.",
                            Features = "Sử dụng trong 1 ngày|Tự động phát thuyết minh khi đến gần POI|Nghe thuyết minh 3 ngôn ngữ|Hỗ trợ review sau khi nghe|!Tinder Ẩm Thực|!AI Kế Hoạch Tour|!Chatbot Thổ Địa",
                            IsActive = true,
                            MaxStores = 0,
                            MonthlyPrice = 50000m,
                            Name = "Tour Basic",
                            Tier = "TourBasic",
                            YearlyPrice = 50000m
                        },
                        new
                        {
                            Id = 8,
                            AllowAiPlanAccess = true,
                            AllowAudioAccess = true,
                            AllowChatbotAccess = true,
                            AllowTinderAccess = true,
                            Audience = "USER",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Trải nghiệm đầy đủ: thuyết minh + Tinder ẩm thực + AI lịch trình + Chatbot tư vấn. Sử dụng trong 1 ngày.",
                            Features = "Sử dụng trong 1 ngày|Tất cả quyền lợi Tour Basic|Tinder Ẩm Thực (quẹt trái/phải)|AI Kế Hoạch Tour từ Groq|Chatbot Thổ Địa tư vấn món ăn|Ưu tiên đề xuất quán hot",
                            IsActive = true,
                            MaxStores = 0,
                            MonthlyPrice = 99000m,
                            Name = "Tour Plus",
                            Tier = "TourPlus",
                            YearlyPrice = 99000m
                        });
                });

            modelBuilder.Entity("PoiApi.Models.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ListenCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("PoiId")
                        .HasColumnType("int");

                    b.Property<string>("QrCodeUrl")
                        .HasColumnType("longtext");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PoiId");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("PoiApi.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("CancelRequestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CheckoutUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GuestEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentLinkId")
                        .HasColumnType("longtext");

                    b.Property<long?>("PaymentOrderCode")
                        .HasColumnType("bigint");

                    b.Property<string>("PaymentProvider")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RevenueRecipientShopId")
                        .HasColumnType("int");

                    b.Property<int?>("RevenueRecipientUserId")
                        .HasColumnType("int");

                    b.Property<int>("ServicePackageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("IX_Subscriptions_DeviceId");

                    b.HasIndex("ServicePackageId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("PoiApi.Models.SwipedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLiked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SwipedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.HasIndex("UserId", "ShopId")
                        .IsUnique();

                    b.ToTable("SwipedItems");
                });

            modelBuilder.Entity("PoiApi.Models.UsageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("GuestId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ListenedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuestId")
                        .HasDatabaseName("IX_UsageHistories_GuestId");

                    b.HasIndex("ShopId");

                    b.ToTable("UsageHistories");
                });

            modelBuilder.Entity("PoiApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("POITranslation", b =>
                {
                    b.HasOne("PoiApi.Models.POI", "POI")
                        .WithMany("Translations")
                        .HasForeignKey("POIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("POI");
                });

            modelBuilder.Entity("PoiApi.Models.Menu", b =>
                {
                    b.HasOne("PoiApi.Models.POI", null)
                        .WithMany("Menus")
                        .HasForeignKey("POIId");

                    b.HasOne("PoiApi.Models.Shop", "Shop")
                        .WithMany("Menus")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("PoiApi.Models.MenuItem", b =>
                {
                    b.HasOne("PoiApi.Models.Menu", "Menu")
                        .WithMany("MenuItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("PoiApi.Models.Order", b =>
                {
                    b.HasOne("PoiApi.Models.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("PoiApi.Models.Review", b =>
                {
                    b.HasOne("PoiApi.Models.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoiApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoiApi.Models.Shop", b =>
                {
                    b.HasOne("PoiApi.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PoiApi.Models.User", "Owner")
                        .WithMany("Shops")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoiApi.Models.POI", "Poi")
                        .WithMany()
                        .HasForeignKey("PoiId");

                    b.Navigation("Category");

                    b.Navigation("Owner");

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("PoiApi.Models.Subscription", b =>
                {
                    b.HasOne("PoiApi.Models.ServicePackage", "ServicePackage")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ServicePackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoiApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ServicePackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoiApi.Models.SwipedItem", b =>
                {
                    b.HasOne("PoiApi.Models.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoiApi.Models.User", "User")
                        .WithMany("SwipedItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoiApi.Models.UsageHistory", b =>
                {
                    b.HasOne("PoiApi.Models.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("PoiApi.Models.User", b =>
                {
                    b.HasOne("PoiApi.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PoiApi.Models.Menu", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("PoiApi.Models.POI", b =>
                {
                    b.Navigation("Menus");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("PoiApi.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PoiApi.Models.ServicePackage", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("PoiApi.Models.Shop", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("PoiApi.Models.User", b =>
                {
                    b.Navigation("Shops");

                    b.Navigation("SwipedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
